os: linux
dist: focal
arch: amd64
sudo: false

language: php

php:
  - '7.4'
  - '8.0'
  - nightly

matrix:
  fast_finish: true

cache:
  directories:
    - $HOME/.composer/cache

before_install:
  - phpenv config-rm xdebug.ini
  - phpenv config-add travis.php.ini
  - composer self-update
  - composer validate

install:
  - travis_retry composer install --prefer-dist

script:
  - php bin/benchmark --iteration=10 --rows=65534 --cells=5 --driver=Spout
  - php bin/benchmark --iteration=10 --rows=65534 --cells=5 --driver=SpreadsheetExcelWriter
  - php bin/benchmark --iteration=10 --rows=65534 --cells=5 --driver=Phpspreadsheet
